<?php



/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends Doctrine\ORM\EntityRepository {

	function getLongFilmsMatchName($name) {

		$all_films = $this->_em->getRepository('Film')->createQueryBuilder('f')
			->where('f.titre LIKE :title')
			->andWhere('f.dureeMinutes > :duration')
			->setParameter('title', '%'.$name.'%')
			->setParameter('duration', 120)
			->orderBy('f.dateDebutAffiche', 'ASC')
			->getQuery()
			->getResult()
		;

		return $all_films;
	}
}
